### ISSUE TITLE
API Test cases from the values that are clearly outside the specified format

### ISSUE THREAD

**Issue by Jhasija9** [binny-chopra/smarter-university-system#28] opened 2023-11-02 15:29 UTC
This Activity is for EPIC #8

As part of this activity Shabnam will create API test inputs for the parameters in such a way that few test cases will have values that are clearly outside the parameters specified format mentioned in the SOW. Utilising the category partition and boundary value analysis methods.

**Comment by sshaikh4** [comment] 2023-11-07 05:18
This is a duplicate of Activity #11, we will reuse this activity for future API or Unit Test activities.

**Comment by sshaikh4** [comment] 2023-11-26 02:52
As mentioned earlier we have used this issues as API Test case activity. The description and Activity name is updated accordingly.

**Comment by sshaikh4** [comment] 2023-11-26 05:59
The API test cases for values that are outside the specified format is created and listed in the below linked excel spreadsheet. I have referred the Statement of Work to use date and time outside the specified format for these test cases.

[API Test Cases](https://docs.google.com/spreadsheets/d/1qqNqNJRoYm7R4czxXrj8OzN9eZC_KIBi/edit#gid=608825545)

**Closed as completed** 2023-11-26 05:59 UTC
Labels: Activity
